[pytest]

testpaths = tests

norecursedirs = venv

addopts = -v -s -W ignore


python_files = test_*.py
python_classes = Test*
python_functions = test_*

pythonpath = .


markers =
    unit:
    integration:
    data_quality: